# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a36fa02addc6d622e7b3b729dd2b40bbc5aee97d8d57940b07fc5990528a9fece4bd82986541b250a667e159ac4eef826538126687488217f17bf53b1ecf3972

test:
  secret_key_base: 9a70b99f49abfb23de19d5b89657421ca393aed50c05cb69f9ef5c2370052a69a6415e9eb589f658499742e4ef354b8005a05326d019c4d5fc2b058bdacdc917

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
